2023-11-21 15:23:46.167920+06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Параметр "#1" не установлен
Parameter "#1" is not set; SQL statement:
INSERT INTO booking (user_id, price, description) VALUES (?, ?, ?) [90012-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.expression.Parameter.checkSet(Parameter.java:75)
	at org.h2.command.Prepared.checkParameters(Prepared.java:207)
	at org.h2.command.CommandContainer.update(CommandContainer.java:159)
	at org.h2.command.Command.executeUpdate(Command.java:256)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:216)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:174)
	at db.DatabaseManager.addBooking(DatabaseManager.java:86)
	at Main.main(Main.java:105)
2023-11-21 15:25:24.559020+06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Недопустимое значение "3" для параметра "parameterIndex"
Invalid value "3" for parameter "parameterIndex" [90008-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1408)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:391)
	at db.DatabaseManager.addBooking(DatabaseManager.java:85)
	at Main.main(Main.java:105)
2023-11-21 19:04:13.376109+06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Недопустимое значение "4" для параметра "parameterIndex"
Invalid value "4" for parameter "parameterIndex" [90008-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1408)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:391)
	at db.DatabaseManager.addBooking(DatabaseManager.java:88)
	at Main.main(Main.java:105)
2023-11-21 19:20:11.656864+06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Недопустимое значение "4" для параметра "parameterIndex"
Invalid value "4" for parameter "parameterIndex" [90008-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1408)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:391)
	at db.DatabaseManager.addBooking(DatabaseManager.java:88)
	at Main.main(Main.java:105)
2023-11-21 19:23:42.229224+06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Недопустимое значение "4" для параметра "parameterIndex"
Invalid value "4" for parameter "parameterIndex" [90008-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1408)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:391)
	at db.DatabaseManager.addBooking(DatabaseManager.java:88)
	at Main.main(Main.java:106)
2023-11-21 19:24:17.362409+06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Недопустимое значение "4" для параметра "parameterIndex"
Invalid value "4" for parameter "parameterIndex" [90008-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1408)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:391)
	at db.DatabaseManager.addBooking(DatabaseManager.java:88)
	at Main.main(Main.java:102)
2023-11-21 19:27:22.570125+06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Недопустимое значение "4" для параметра "parameterIndex"
Invalid value "4" for parameter "parameterIndex" [90008-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1408)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:391)
	at db.DatabaseManager.addBooking(DatabaseManager.java:87)
	at Main.main(Main.java:98)
2023-11-21 19:55:28.000537+06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Объект уже закрыт
The object is already closed [90007-224]
2023-11-21 19:55:28.004543+06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Объект уже закрыт
The object is already closed [90007-224]
2023-11-21 19:57:12.206842+06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Объект уже закрыт
The object is already closed [90007-224]
2023-11-21 19:57:12.210846+06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Объект уже закрыт
The object is already closed [90007-224]
2023-11-21 19:58:35.113678+06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Объект уже закрыт
The object is already closed [90007-224]
2023-11-21 20:40:34.605236+06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Столбец "PRICE" не найден
Column "PRICE" not found; SQL statement:
UPDATE users SET password = ?, price = ?, description = ? WHERE name = ? [42122-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:759)
	at org.h2.command.Parser.readTableColumn(Parser.java:984)
	at org.h2.command.Parser.readUpdateSetClause(Parser.java:1071)
	at org.h2.command.Parser.parseUpdate(Parser.java:1024)
	at org.h2.command.Parser.parsePrepared(Parser.java:765)
	at org.h2.command.Parser.parse(Parser.java:592)
	at org.h2.command.Parser.parse(Parser.java:564)
	at org.h2.command.Parser.prepareCommand(Parser.java:483)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:639)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:559)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1166)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:93)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:316)
	at db.DatabaseManager.updateUserIfExists(DatabaseManager.java:262)
	at Main.handleUser(Main.java:139)
	at Main.main(Main.java:37)
2023-11-21 20:44:39.673772+06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Столбец "PRICE" не найден
Column "PRICE" not found; SQL statement:
UPDATE users SET password = ?, price = ?, description = ? WHERE name = ? [42122-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:759)
	at org.h2.command.Parser.readTableColumn(Parser.java:984)
	at org.h2.command.Parser.readUpdateSetClause(Parser.java:1071)
	at org.h2.command.Parser.parseUpdate(Parser.java:1024)
	at org.h2.command.Parser.parsePrepared(Parser.java:765)
	at org.h2.command.Parser.parse(Parser.java:592)
	at org.h2.command.Parser.parse(Parser.java:564)
	at org.h2.command.Parser.prepareCommand(Parser.java:483)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:639)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:559)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1166)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:93)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:316)
	at db.DatabaseManager.updateUserIfExists(DatabaseManager.java:262)
	at Main.handleUser(Main.java:139)
	at Main.main(Main.java:37)
2023-11-21 20:46:45.163263+06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Столбец "PRICE" не найден
Column "PRICE" not found; SQL statement:
UPDATE users SET password = ?, price = ?, description = ? WHERE name = ? [42122-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:759)
	at org.h2.command.Parser.readTableColumn(Parser.java:984)
	at org.h2.command.Parser.readUpdateSetClause(Parser.java:1071)
	at org.h2.command.Parser.parseUpdate(Parser.java:1024)
	at org.h2.command.Parser.parsePrepared(Parser.java:765)
	at org.h2.command.Parser.parse(Parser.java:592)
	at org.h2.command.Parser.parse(Parser.java:564)
	at org.h2.command.Parser.prepareCommand(Parser.java:483)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:639)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:559)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1166)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:93)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:316)
	at db.DatabaseManager.updateUserIfExists(DatabaseManager.java:262)
	at Main.handleUser(Main.java:139)
	at Main.main(Main.java:37)
2023-11-21 21:26:10.760237+06:00 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/77089/Desktop/SDPFinal/data/sample.mv.db [2.2.224/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/77089/Desktop/SDPFinal/data/sample.mv.db [2.2.224/7]" [50000-224]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:407)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:122)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:1546)
	at org.h2.mvstore.MVStore.panic(MVStore.java:371)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:291)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)
	at org.h2.mvstore.db.Store.<init>(Store.java:133)
	at org.h2.engine.Database.<init>(Database.java:326)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:343)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:125)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at db.DatabaseManager.initializeDatabase(DatabaseManager.java:31)
	at db.DatabaseManager.<init>(DatabaseManager.java:19)
	at db.DatabaseManager.main(DatabaseManager.java:273)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/77089/Desktop/SDPFinal/data/sample.mv.db [2.2.224/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/77089/Desktop/SDPFinal/data/sample.mv.db [2.2.224/7]" [50000-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:566)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 20 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/77089/Desktop/SDPFinal/data/sample.mv.db [2.2.224/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:286)
	... 14 more
2023-11-21 21:30:19.942209+06:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Подзапрос выбирает более одной строки
Scalar subquery contains more than one row; SQL statement:
DELETE FROM booking WHERE user_id = (SELECT id FROM users WHERE name = ?) [90053-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.expression.Subquery.getValue(Subquery.java:53)
	at org.h2.index.IndexCondition.getCurrentValue(IndexCondition.java:152)
	at org.h2.index.IndexCursor.prepare(IndexCursor.java:111)
	at org.h2.index.IndexCursor.find(IndexCursor.java:158)
	at org.h2.table.TableFilter.next(TableFilter.java:394)
	at org.h2.command.dml.FilteredDataChangeStatement.nextRow(FilteredDataChangeStatement.java:71)
	at org.h2.command.dml.Delete.update(Delete.java:58)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:256)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:216)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:174)
	at db.DatabaseManager.deleteUserAndBooking(DatabaseManager.java:105)
	at Main.handleUser(Main.java:137)
	at Main.main(Main.java:37)
